### ISSUE TITLE
Python codec error on last release

### ISSUE THREAD

**Issue by Dr4s1l** [whad-team/whad-client#29]
Since last realese, reinstalling whad-client give me a error on whadup command despite the encoding specified in main binary :

```
└─[0] <git:(main 3dcb27d) > whadup
[i] Available devices
Traceback (most recent call last):
  File "/home/anon/Tools/whad-client/bin/whadup", line 8, in <module>
    sys.exit(main())
  File "/home/anon/Tools/whad-client/lib/python3.8/site-packages/whad/tools/whadup.py", line 216, in main
    for device in WhadDevice.list(): #print('Usage: %s [device]' % sys.argv[0])
  File "/home/anon/Tools/whad-client/lib/python3.8/site-packages/whad/device/__init__.py", line 696, in list
    for device in device_class.list():
  File "/home/anon/Tools/whad-client/lib/python3.8/site-packages/whad/device/unix.py", line 47, in list
    proc_net_unix = open('/proc/net/unix','r').read()
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf7 in position 5786: invalid start byte
```
For what I understand there are issue on /proc/net/unix encoding interpretation.
Another error occurs also on examples/ble_advertisements_sniffer.py with some character not correctly decoded but came for my venv using python2. I think the above error is not related.

Everythings works fine when adding the interface uart0 parameter

**Comment by nrathaus** [comment]
This seems to be an unanswered thread, I can shed some light as I am experiencing similar issues
```
0000000000000000: 00000002 00000000 00000000 0002 01 22884 @@@@<F3>^C@@^?^\
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
```

If I look at the output of my `/proc/net/unix` I can see this

I do not know the underlying reason for these characters and what they mean

Hexdump (if it helps):
```
00001020  32 32 38 38 34 20 40 40  40 40 f3 03 40 40 7f 1c  |22884 @@@@..@@..|
00001030  0a 40 40 40 40 40 40 40  40 40 40 40 40 40 40 40  |.@@@@@@@@@@@@@@@|
00001040  40 40 40 40 40 40 40 40  40 40 40 40 40 40 40 40  |@@@@@@@@@@@@@@@@|
*
00001090  40 40 0a 30 30 30 30 30  30 30 30 30 30 30 30 30  |@@.0000000000000|
000010a0  30 30 30 3a 20 30 30 30  30 30 30 30 32 20 30 30  |000: 00000002 00|
```

**Comment by virtualabs** [comment]
Nice catch, will fix this soon.
