### ISSUE TITLE
whad.exceptions.WhadDeviceNotReady

### ISSUE THREAD

**Issue by jsmif** [whad-team/whad-client#45]
I'm trying to run the suggested CLI command from https://whad.readthedocs.io/en/stable/cli/index.html

On Ubuntu 22.04 (python version 3.10.12, wireshark at version 3.6.2-2)

sudo pip3 install whad

```
hciconfig
hci0:	Type: Primary  Bus: USB
	BD Address: 56:1A:34:DA:12:0A  ACL MTU: 310:10  SCO MTU: 64:8
	UP RUNNING 
	RX bytes:1250 acl:0 sco:0 events:55 errors:0
	TX bytes:3186 acl:0 sco:0 commands:55 errors:0
```

```
sudo wble-connect -i hci0 12:4A:7f:2C:C3:29 | wshark 
Whad device is not ready.
[!] An unexpected exception occured:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/whad/cli/app.py", line 716, in run_app
    application.run()
  File "/usr/local/lib/python3.10/dist-packages/whad/ble/cli/ble_connect.py", line 264, in run
    self.connect_target(self.args.bdaddr, self.args.random)
  File "/usr/local/lib/python3.10/dist-packages/whad/ble/cli/ble_connect.py", line 325, in connect_target
    central = Central(self.interface)
  File "/usr/local/lib/python3.10/dist-packages/whad/ble/connector/central.py", line 35, in __init__
    super().__init__(device)
  File "/usr/local/lib/python3.10/dist-packages/whad/ble/connector/__init__.py", line 80, in __init__
    self.device.open()
  File "/usr/local/lib/python3.10/dist-packages/whad/device/virtual/hci/__init__.py", line 124, in open
    raise WhadDeviceNotReady()
whad.exceptions.WhadDeviceNotReady
```

I can run commands like `bluetoothctl scan on` to scan for devices with this hci0 device just fine, so I know it's working.

I also did `sudo wble-connect -i hci0 12:4A:7f:2C:C3:29 | wshark | wble-central profile` and that gives the same error + the additional error of `[!] You need to specify a target device with option --bdaddr.` (so the documentation for wble-central may be wrong now and needs a -b by default?)

Also, in case it matters, the USB BT dongle in use is a CSR one which is known to be able to spoof its bdaddr when used with GATTacker for instance.

**Comment by virtualabs** [comment]
Using USB BT dongles with WHAD requires some privileges and this can be solved by installing the correct udev rules on your system. We provide a setup script to automate this, just run in the project directory:

```
$ sudo python3 setup.py devices_install
```

It should install all the required rules for CSR4 USB dongles on your system and you will be able to use them with WHAD. 

I guess we forgot to mention this in the documentation, we'll fix this soon.

**Comment by virtualabs** [comment]
Allright, I removed the capabilities set by our setup script from my Python interpreter executable to have a setup similar as yours. I am using a virtual environment in which I ran `pip install whad`. 

When I run `wble-connect -i hci1 a4:c1:38:60:fc:5c | wshark | wble-central profile`, targeting a device close to me, I have the following error:

```
$ wble-connect -i hci1 a4:c1:38:60:fc:5c | wshark | wble-central profile
[!] Cannot access WHAD adapter, check permissions.
[!] You need to specify a target device with option --bdaddr.
```
If I use `sudo` then my system throws some errors as it cannot find the requested executables (`wble-connect`, `wshark` and `wble-central`). 

When I run the same command line on my previous configuration (virtualenv + pip install whad + sudo python3 setup.py devices_install) everything is working fine.

I have some questions then:

- Are you using a virtual environment to run WHAD?
- It looks like your system correctly finds WHAD executables even when they are run with sudo, have you installed WHAD as root or system-wide ?

You can also try to clone the repository and then create a virtual environment as root:

```
$ git clone https://github.com/whad-team/whad-client.git
$ cd whad-client
$ sudo su
# python3 -m venv venv-root
# . ./venv-root/bin/activate
# pip install .
```
And then use WHAD's CLI tools and see if it works better, or not.

**Comment by virtualabs** [comment]
I see, we definitely need to improve the instructions to ease the installation and avoid further issues. And maybe move the code from `setup.py` into a small CLI tool to configure the system in order to allow using BT USB dongles as user.

Thank you for reporting this anyway, we'll do our best to improve the framework and its documentation (and fix issues too :smile:). Keep us posted if you managed to connect to a device and interact with it or if nothing works as expect.
