### ISSUE TITLE
Crash while listing devices `wup`

### ISSUE THREAD

**Issue by georgehedfors** [whad-team/whad-client#79]
`System Version: macOS 15.0.1 (24A348)   Kernel Version: Darwin 24.0.0`

% wup
WARNING: No IPv4 address found on anpi1 !
WARNING: No IPv4 address found on anpi0 !
WARNING: more No IPv4 address found on anpi2 !
[i] Available devices
Cannot access RFStorm, root privileges may be required.
Cannot access YardStickOne, root privileges may be required.
Traceback (most recent call last):
  File "/opt/miniconda3/envs/whad-workshop/bin/wup", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/miniconda3/envs/whad-workshop/lib/python3.11/site-packages/whad/tools/whadup.py", line 250, in main
    for device in WhadDevice.list(): #print('Usage: %s [device]' % sys.argv[0])
                  ^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/whad-workshop/lib/python3.11/site-packages/whad/device/__init__.py", line 985, in list
    device_class_list = device_class.list()
                        ^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/whad-workshop/lib/python3.11/site-packages/whad/device/virtual/hci/__init__.py", line 78, in list
    devices_ids = HCIConfig.list()
                  ^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/whad-workshop/lib/python3.11/site-packages/whad/device/virtual/hci/hciconfig.py", line 17, in list
    sock = socket(31, SOCK_RAW, 1)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/whad-workshop/lib/python3.11/socket.py", line 232, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 47] Address family not supported by protocol family

**Comment by khenissimehdi** [comment]
having the same issues here when I run the command whadup

System: Mac OS Apple M3 version 15.6 
```
[i] Available devices
Traceback (most recent call last):
  File "/Users/mehdi/.pyenv/versions/3.12.0/bin/whadup", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/mehdi/.pyenv/versions/3.12.0/lib/python3.12/site-packages/whad/tools/whadup.py", line 304, in main
    for device in WhadDevice.list(): #print("Usage: %s [device]" % sys.argv[0])
                  ^^^^^^^^^^^^^^^^^
  File "/Users/mehdi/.pyenv/versions/3.12.0/lib/python3.12/site-packages/whad/device/device.py", line 328, in list
    device_class_list = device_class.list()
                        ^^^^^^^^^^^^^^^^^^^
  File "/Users/mehdi/.pyenv/versions/3.12.0/lib/python3.12/site-packages/whad/device/virtual/hci/__init__.py", line 234, in list
    devices_ids = HCIConfig.list()
                  ^^^^^^^^^^^^^^^^
  File "/Users/mehdi/.pyenv/versions/3.12.0/lib/python3.12/site-packages/whad/device/virtual/hci/hciconfig.py", line 23, in list
    sock = socket(31, SOCK_RAW, 1)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mehdi/.pyenv/versions/3.12.0/lib/python3.12/socket.py", line 233, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 47] Address family not supported by protocol family
LAP-LL9N34G304 :: ~ 1 »
```
